# This is a default home.nix generated by the follwing hone-manager command
#
# home-manager init ./
{ config, lib, pkgs, ... }:

{
  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home.username = lib.mkDefault "pharo";
  home.homeDirectory = lib.mkDefault "/home/${config.home.username}";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  #
  # You should not change this value, even if you update Home Manager. If you do
  # want to update the value, then make sure to first check the Home Manager
  # release notes.
  home.stateVersion = "24.05"; # Please read the comment before changing.

  # The home.packages option allows you to install Nix packages into your
  # environment.
  # NOTE: I added zed remove or something idk
  # NOTE: I added todoist-electron delete later
  home.packages = with pkgs; [ tmux-sessionizer zed-editor todoist-electron ];

  home.sessionVariables = {
    EDITOR = "nvim";
    TERMINAL = "kitty";
    NIX_PATH = "nixpkgs=channel:nixos-unstable";
    NIX_LOG = "info";
    # PROJECT_DIRS = builtins.concatStringsSep " " [ "$HOME" "$HOME/Projects/" ];
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;
}
